apiVersion: apps/v1                                                                                                                                                 
kind: Deployment
metadata:
  name: ng
spec:
  selector:
    matchLabels:
      app: ng
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.5
        ports:
        - containerPort: 9100
