apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cosignkey-webhook-server-cert
  namespace: cosign
spec:
  dnsNames:
  - cosignkey-webhook.cosign.svc
  - cosignkey-webhook.cosign.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cosignkey-selfsigned-issuer
  secretName: cosignkey-webhook-server-cert