kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosignkey-webhook
subjects:
- kind: ServiceAccount
  name: cosignkey-webhook
  namespace: cosign
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cosignkey-webhook
  apiGroup: rbac.authorization.k8s.io