apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosignkey-webhook
  namespace: cosign
  labels:
    app: cosignkey-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cosignkey-webhook
  template:
    metadata:
      labels:
        app: cosignkey-webhook
    spec:
      serviceAccountName: cosignkey-webhook
      terminationGracePeriodSeconds: 10
      containers:
      - name: webhook-server
        image: dongjiang1989/cosign-webhook:master
        ports:
        - containerPort: 9443
          name: webhook
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: probe
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - mountPath: /etc/webhook/certs/
            name: cert
            readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: cosignkey-webhook-server-cert