apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-cosignkey-webhook-configuration
  namespace: cosign
  labels:
    app: mutating-cosignkey-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: cosign/cosignkey-webhook-server-cert
webhooks:
  - name: cosignkey-webhook.cosign.svc
    clientConfig:
      service:
        name: cosignkey-webhook
        namespace: cosign
        path: "/mutate-cosign-verify"
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        cosignkey.kubernetes.io/verify : enabled