kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosignkey-webhook
  namespace: cosign
subjects:
- kind: ServiceAccount
  name: cosignkey-webhook
  namespace: cosign
  apiGroup: ""
roleRef:
  kind: Role
  name: cosignkey-webhook
  apiGroup: rbac.authorization.k8s.io