apiVersion: v1
kind: Service
metadata:
  name: cosignkey-webhook-service
  namespace: cosign
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: cosignkey-webhook